packages:
  - apps/*
  - packages/*

overrides:
  js-yaml: 4.3.2
  shell-quote: 1.10.0

allowBuilds:
  '@electron/rebuild': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
